# -*- coding: utf-8 -*-
"""ML DDOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JS5BodeF_UKr-_hYd12ynPWg0ljbdP0s

### Import Library
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/ML/dataset_sdn.csv')
df.head()

"""### Pemrosesan Data

#### Pengecekan baris dan kolom
"""

print("This Dataset has {} rows and {} columns".format(df.shape[0], df.shape[1]))

"""#### Menunjukan Type data dari kolom

"""

df.info()

"""#### Nilai statistik dataset"""

df.describe()

"""#### heatmap Nilai yang hilang"""

msno.matrix(df)

"""#### Menghitung nilai kosong dari fitur"""

df.isnull().sum()

(df.isnull().sum()/df.isnull().count())*100

"""#### Menghapus kolom dengan nilai null"""

df.dropna(inplace=True)

"""#### Pengecekan nilai null"""

print(df.isnull().sum())
print("This Dataframe has {} rows and {} columns after removing null values".format(df.shape[0], df.shape[1]))

"""#### distribusi kelas label"""

malign = df[df['label'] == 1]
benign = df[df['label'] == 0]

print('Number of DDOS attacks that has occured :',round((len(malign)/df.shape[0])*100,2),'%')
print('Number of DDOS attacks that has not occured :',round((len(benign)/df.shape[0])*100,2),'%')

"""#### Numerical Features"""

numerical_features = [feature for feature in df.columns if df[feature].dtypes != 'O']
print("The number of numerical features is",len(numerical_features),"and they are : \n",numerical_features)

"""#### Categorical Features"""

categorical_features = [feature for feature in df.columns if df[feature].dtypes == 'O']
print("The number of categorical features is",len(categorical_features),"and they are : \n",categorical_features)

"""#### Gabut"""

# number of unique values in each numerical variable
df[numerical_features].nunique(axis=0)

"""#### Ngecek nilai discrete"""

#discrete numerical features
discrete_feature = [feature for feature in numerical_features if df[feature].nunique()<=15 and feature != 'label']
print("The number of discrete features is",len(discrete_feature),"and they are : \n",discrete_feature)

df[discrete_feature].head(10)

"""#### Nilai continuos"""

continuous_feature=[feature for feature in numerical_features if feature not in discrete_feature + ['label']]
print("The number of continuous_feature features is",len(continuous_feature),"and they are : \n",continuous_feature)

"""### Encoding"""

df = pd.get_dummies(df, columns=categorical_features,drop_first=True)
print("This Dataframe has {} rows and {} columns after encoding".format(df.shape[0], df.shape[1]))

#dataframe after encoding
df.head(10)

df.dtypes

"""### Memisahkan label"""

#separating input and output attributes
x = df.drop(['label'], axis=1)
y = df['label']

"""### Normalisasi fitur"""

ms = MinMaxScaler()
x = ms.fit_transform(x)

"""### Train-Test-Split [70-30]"""

X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.3)
print(X_train.shape, X_test.shape)

"""##Smote"""

from imblearn.over_sampling import SMOTE
from sklearn import metrics

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print(f"Jumlah data sebelum SMOTE: {len(y_train)}")
print(f"Jumlah data setelah SMOTE: {len(y_train_smote)}")

y_train_series = pd.Series(y_train)
y_train_smote_series = pd.Series(y_train_smote)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.countplot(x=y_train_series, ax=axes[0], palette='viridis')
axes[0].set_title('Distribusi Kelas Sebelum SMOTE')
axes[0].set_xlabel('Kelas Target')
axes[0].set_ylabel('Jumlah Data')

for p in axes[0].patches:
    axes[0].annotate(f'{int(p.get_height())}',
                     (p.get_x() + p.get_width() / 2., p.get_height()),
                     ha='center', va='bottom')

sns.countplot(x=y_train_smote_series, ax=axes[1], palette='viridis')
axes[1].set_title('Distribusi Kelas Setelah SMOTE')
axes[1].set_xlabel('Kelas Target')
axes[1].set_ylabel('Jumlah Data')

for p in axes[1].patches:
    axes[1].annotate(f'{int(p.get_height())}',
                     (p.get_x() + p.get_width() / 2., p.get_height()),
                     ha='center', va='bottom')

plt.tight_layout()
plt.show()

Classifier_accuracy = []

"""## Pencarian Model

#### SVM Classifier
"""

# 1. Latih model SVM menggunakan data yang sudah diseimbangkan (SMOTE)
svc_clf = SVC()
svc_clf.fit(X_train_smote, y_train_smote)

# 2. Lakukan prediksi pada data testing asli (X_test)
y_pred = svc_clf.predict(X_test)

# 3. Hitung Metrik Evaluasi secara individu
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Pastikan list Classifier_accuracy sudah didefinisikan sebelumnya
Classifier_accuracy.append(accuracy * 100)

# Menampilkan hasil evaluasi dengan rapi
print("=== Hasil Evaluasi Model SVM (dengan SMOTE) ===")
print("Akurasi   : {:.2f}%".format(accuracy * 100))
print("Presisi   : {:.2f}%".format(precision * 100))
print("Recall    : {:.2f}%".format(recall * 100))
print("F1-Score  : {:.2f}%".format(f1 * 100))
print("-" * 47)

# 4. Membuat dan Menampilkan Visualisasi Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
# Heatmap untuk visualisasi matrix
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Normal (0)', 'DDoS (1)'],
            yticklabels=['Normal (0)', 'DDoS (1)'])

plt.title('Confusion Matrix - SVM (with SMOTE)', pad=20, fontsize=14)
plt.ylabel('Label Sebenarnya (True)', fontsize=12)
plt.xlabel('Label Prediksi (Predicted)', fontsize=12)
plt.show()

"""### Logistic Regression"""

# MODEL: LOGISTIC REGRESSION
# 1. Latih model Logistic Regression menggunakan data yang sudah diseimbangkan (SMOTE)
logreg_clf = LogisticRegression(max_iter=1000, random_state=42)
logreg_clf.fit(X_train_smote, y_train_smote)

# 2. Lakukan prediksi pada data testing asli (X_test)
y_pred_logreg = logreg_clf.predict(X_test)

# 3. Hitung Metrik Evaluasi secara individu
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
precision_logreg = precision_score(y_test, y_pred_logreg)
recall_logreg = recall_score(y_test, y_pred_logreg)
f1_logreg = f1_score(y_test, y_pred_logreg)

# Menyimpan akurasi ke dalam list (pastikan Classifier_accuracy sudah didefinisikan)
Classifier_accuracy.append(accuracy_logreg * 100)

# Menampilkan hasil evaluasi dengan rapi
print("=== Hasil Evaluasi Model Logistic Regression (dengan SMOTE) ===")
print("Akurasi   : {:.2f}%".format(accuracy_logreg * 100))
print("Presisi   : {:.2f}%".format(precision_logreg * 100))
print("Recall    : {:.2f}%".format(recall_logreg * 100))
print("F1-Score  : {:.2f}%".format(f1_logreg * 100))
print("-" * 63)

# 4. Membuat dan Menampilkan Visualisasi Confusion Matrix
cm_logreg = confusion_matrix(y_test, y_pred_logreg)

plt.figure(figsize=(8, 6))
# Heatmap untuk visualisasi matrix
sns.heatmap(cm_logreg, annot=True, fmt='d', cmap='Oranges', cbar=False,
            xticklabels=['Normal (0)', 'DDoS (1)'],
            yticklabels=['Normal (0)', 'DDoS (1)'])

plt.title('Confusion Matrix - Logistic Regression (with SMOTE)', pad=20, fontsize=14)
plt.ylabel('Label Sebenarnya (True)', fontsize=12)
plt.xlabel('Label Prediksi (Predicted)', fontsize=12)
plt.show()

"""### XgBoost"""

# MODEL: XGBOOST
# 1. Latih model XGBoost menggunakan data yang sudah diseimbangkan (SMOTE)
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_clf.fit(X_train_smote, y_train_smote)

# 2. Lakukan prediksi pada data testing asli (X_test)
y_pred_xgb = xgb_clf.predict(X_test)

# 3. Hitung Metrik Evaluasi secara individu
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)

# Menyimpan akurasi ke dalam list
Classifier_accuracy.append(accuracy_xgb * 100)

# Menampilkan hasil evaluasi dengan rapi
print("=== Hasil Evaluasi Model XGBoost (dengan SMOTE) ===")
print("Akurasi   : {:.2f}%".format(accuracy_xgb * 100))
print("Presisi   : {:.2f}%".format(precision_xgb * 100))
print("Recall    : {:.2f}%".format(recall_xgb * 100))
print("F1-Score  : {:.2f}%".format(f1_xgb * 100))
print("-" * 51)

# 4. Membuat dan Menampilkan Visualisasi Confusion Matrix
cm_xgb = confusion_matrix(y_test, y_pred_xgb)

plt.figure(figsize=(8, 6))
# Heatmap untuk visualisasi matrix
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Greens', cbar=False,
            xticklabels=['Normal (0)', 'DDoS (1)'],
            yticklabels=['Normal (0)', 'DDoS (1)'])

plt.title('Confusion Matrix - XGBoost (with SMOTE)', pad=20, fontsize=14)
plt.ylabel('Label Sebenarnya (True)', fontsize=12)
plt.xlabel('Label Prediksi (Predicted)', fontsize=12)
plt.show()

"""## Pengecekan Overfiting Setiap Model"""

print("\n" + "="*55)
print("=== ANALISIS OVERFITTING / GENERALISASI MODEL ===")
print("="*55)

# Fungsi bantuan untuk mencetak hasil dengan rapi
def print_overfitting_status(model_name, acc_train, acc_test):
    gap = acc_train - acc_test
    print(f"\nModel: {model_name}")
    print(f"Akurasi Data Training : {acc_train:.2f}%")
    print(f"Akurasi Data Testing  : {acc_test:.2f}%")
    print(f"Selisih (Gap)         : {gap:.2f}%")

    # Aturan sederhana: Jika selisih > 5%, indikasi overfitting
    if gap > 5.0:
        print("Status : Indikasi OVERFITTING (Model menghafal data training)")
    elif gap < -2.0:
        print("Status : Indikasi UNDERFITTING (Periksa kembali datanya)")
    else:
        print("Status : GOOD FIT (Model sudah optimal)")

# 1. Lakukan Prediksi menggunakan Data Training (SMOTE)
y_pred_train_svm = svc_clf.predict(X_train_smote)
y_pred_train_logreg = logreg_clf.predict(X_train_smote)
y_pred_train_xgb = xgb_clf.predict(X_train_smote)

# 2. Hitung Akurasi Training
acc_train_svm = accuracy_score(y_train_smote, y_pred_train_svm) * 100
acc_train_logreg = accuracy_score(y_train_smote, y_pred_train_logreg) * 100
acc_train_xgb = accuracy_score(y_train_smote, y_pred_train_xgb) * 100

# 3. Ambil Akurasi Testing dari variabel yang sudah Anda definisikan sebelumnya
acc_test_svm = accuracy * 100
acc_test_logreg = accuracy_logreg * 100
acc_test_xgb = accuracy_xgb * 100

# Hasil
print_overfitting_status("SVM", acc_train_svm, acc_test_svm)
print_overfitting_status("Logistic Regression", acc_train_logreg, acc_test_logreg)
print_overfitting_status("XGBoost", acc_train_xgb, acc_test_xgb)
print("\n" + "="*55)

"""## Hasil ROC"""

# 1. Dapatkan nilai probabilitas / skor prediksi untuk masing-masing model

y_score_svm = svc_clf.decision_function(X_test)
y_score_logreg = logreg_clf.predict_proba(X_test)[:, 1]
y_score_xgb = xgb_clf.predict_proba(X_test)[:, 1]

# 2. Hitung False Positive Rate (FPR), True Positive Rate (TPR), dan AUC
# SVM
fpr_svm, tpr_svm, _ = roc_curve(y_test, y_score_svm)
roc_auc_svm = auc(fpr_svm, tpr_svm)

# Logistic Regression
fpr_logreg, tpr_logreg, _ = roc_curve(y_test, y_score_logreg)
roc_auc_logreg = auc(fpr_logreg, tpr_logreg)

# XGBoost
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, y_score_xgb)
roc_auc_xgb = auc(fpr_xgb, tpr_xgb)

# 3. Buat Visualisasi ROC Curve
plt.figure(figsize=(10, 8))
plt.plot(fpr_svm, tpr_svm, color='blue', lw=2,
         label='SVM (AUC = %0.4f)' % roc_auc_svm)
plt.plot(fpr_logreg, tpr_logreg, color='darkorange', lw=2,
         label='Logistic Regression (AUC = %0.4f)' % roc_auc_logreg)
plt.plot(fpr_xgb, tpr_xgb, color='green', lw=2,
         label='XGBoost (AUC = %0.4f)' % roc_auc_xgb)

plt.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--', label='Random Guess')

# Pengaturan tata letak plot
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)', fontsize=12)
plt.ylabel('True Positive Rate (TPR)', fontsize=12)
plt.title('Receiver Operating Characteristic (ROC) Curve', fontsize=15, pad=15)
plt.legend(loc="lower right", fontsize=11)
plt.grid(alpha=0.3)

# Tampilkan grafik
plt.show()

"""##Grafik Perbandingan Model"""

# 1. Menyiapkan data untuk grafik
model_names = ['SVM', 'Logistic Regression', 'XGBoost']
model_accuracies = [acc_test_svm, acc_test_logreg, acc_test_xgb]

# 2. Menentukan warna yang berbeda untuk masing-masing model
colors = ['#1f77b4', '#ff7f0e', '#2ca02c']

# 3. Membuat grafik batang
plt.figure(figsize=(9, 6))
bars = plt.bar(model_names, model_accuracies, color=colors, width=0.6)

# 4. Menambahkan label persentase tepat di atas setiap batang
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1.5,
             f'{yval:.2f}%',
             ha='center', va='bottom', fontsize=12, fontweight='bold')

# 5. Pengaturan tata letak dan estetika grafik
plt.title('Perbandingan Akurasi Model Deteksi DDoS', fontsize=15, pad=20, fontweight='bold')
plt.xlabel('Algoritma Machine Learning', fontsize=12, labelpad=10)
plt.ylabel('Akurasi Testing (%)', fontsize=12, labelpad=10)
plt.ylim(0, 115)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# 6. Menampilkan akurasi
best_idx = np.argmax(model_accuracies)
best_model_name = model_names[best_idx]
max_acc = model_accuracies[best_idx]
print(f"Berdasarkan grafik, model terbaik adalah **{best_model_name}** dengan akurasi {max_acc:.2f}%")

plt.show()

"""##Menyimpan Model Terbaik"""

import joblib

# 1. Menyimpan Scaler
# Menggunakan objek MinMaxScaler 'ms' yang sudah di-fit sebelumnya
joblib.dump(ms, 'scaler_ddos.pkl')
print("✅ Scaler berhasil disimpan sebagai 'scaler_ddos.pkl'")
print("-" * 50)

# 2. Mengumpulkan model dan akurasi yang sudah dihitung sebelumnya
models_info = [
    {"name": "SVM", "model": svc_clf, "accuracy": accuracy},
    {"name": "Logistic Regression", "model": logreg_clf, "accuracy": accuracy_logreg},
    {"name": "XGBoost", "model": xgb_clf, "accuracy": accuracy_xgb}
]

# 3. Mencari model dengan akurasi tertinggi
best_model_info = max(models_info, key=lambda x: x["accuracy"])

best_model_name = best_model_info["name"]
best_model = best_model_info["model"]
best_accuracy = best_model_info["accuracy"]

print(f"🏆 Model terbaik adalah {best_model_name} dengan akurasi {best_accuracy*100:.2f}%")

# 4. Menyimpan Model Terbaik
joblib.dump(best_model, 'best_model_ddos.pkl')
print(f"✅ Model {best_model_name} berhasil disimpan sebagai 'best_model_ddos.pkl'")